In [1]:
# Use a linear regression (in scikit-learn , linear Regression)
# Load libraries and data

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [3]:
# Load data with only 2 features
boston=load_boston()
features=boston.data[:,0:2]
target=boston.target

In [4]:
# Create Linear regression
regression=LinearRegression()

In [8]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [5]:
# Fit the linear regression
model=regression.fit(features,target)

In [6]:
# View the intercept
model.intercept_

22.485628113468223

In [7]:
# view the feature coefficients 
model.coef_

array([-0.35207832,  0.11610909])

In [9]:
# First value in the target vector multiplied by 1000
target[0]

24.0

In [10]:
# predict the target value of the first observation
model.predict(features)[0]

24.573366631705547

In [11]:
# Dependant Variable

In [12]:
# Create an interaction term to capture that dependence using scikit learn's Polynomial Features

In [13]:
# Load Libraries

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

In [15]:
# Load data with only two features
boston=load_boston()
features=boston.data[:,0:2]
target=boston.target

In [16]:
# create interaction term
interaction=PolynomialFeatures(degree=3,include_bias=False,interaction_only=True)
features_interaction=interaction.fit_transform(features)

In [17]:
# Create Linear Regression
regression=LinearRegression()

In [18]:
# Fit the linear Regression
model=regression.fit(features_interaction,target)

In [20]:
# View the feature values for the first Observation
features[0]

array([6.32e-03, 1.80e+01])

In [21]:
# Import Library
import numpy as np

In [22]:
# For each Observation , multiply the values of the first and second feature
interaction_term=np.multiply(features[:,0],features[:,1])

In [23]:
# View interaction term for first Observation
interaction_term[0]

0.11376

In [24]:
# View the values of the first observation
features_interaction[0]

array([6.3200e-03, 1.8000e+01, 1.1376e-01])

# Fitting A Non Linear Regression

In [25]:
# Load Library
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
from sklearn.preprocessing import PolynomialFeatures

In [26]:
# Load data with One Feature
boston=load_boston()
features=boston.data[:,0:1]
target=boston.target

In [27]:
# Create Polynomial features x^2 and x^3
polynomial=PolynomialFeatures(degree=3,include_bias=False)
features_polynomial=polynomial.fit_transform(features)

In [28]:
# Create Linear regression
regression=LinearRegression()

In [29]:
# Fit the linear Regression
model=regression.fit(features_polynomial,target)

In [30]:
# View first observation
features[0]

array([0.00632])

In [32]:
# view first Observation raised to the second power , x^2
features[0]**2

array([3.99424e-05])

In [33]:
# view first Observation raised to the third power , x^3
features[0]**3

array([2.52435968e-07])

In [34]:
# view first Observation's values for x , x^2 , x^3
features_polynomial[0]

array([6.32000000e-03, 3.99424000e-05, 2.52435968e-07])

# Reducing Variance with Regularization

In [35]:
# Use a learning algorithm that includes a shrinkage penalty ( as called as regularization) like

In [36]:
#Load Libraries
from sklearn.linear_model import Ridge
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

In [37]:
# Load data
boston=load_boston()
features=boston.data
target=boston.target

In [38]:
#Standardize features
scaler=StandardScaler()

In [39]:
features_standardized=scaler.fit_transform(features)

In [40]:
# Create Ridge regression with an alpha value
regression=Ridge(alpha=0.5)

In [41]:
# Fit the linear regression
model=regression.fit(features_standardized,target)

In [42]:
# Load Library
from sklearn.linear_model import RidgeCV

In [43]:
# Create ridge regression with three alpha values
regr_cv=RidgeCV(alphas=[0.1,1.0,10.0])

In [44]:
# Fit the linear regression
model_cv=regr_cv.fit(features_standardized,target)

In [45]:
# View Coefficients
model_cv.coef_

array([-0.91987132,  1.06646104,  0.11738487,  0.68512693, -2.02901013,
        2.68275376,  0.01315848, -3.07733968,  2.59153764, -2.0105579 ,
       -2.05238455,  0.84884839, -3.73066646])

In [46]:
# View alpha
model_cv.alpha_

1.0